# DATA
#dataset: 'kitchen-complete-v0'
#preprocess_fns: ['only_trajectory','joints_to_cart','cart_to_se3']

loader: 'datasets.GeneratedDataset'
dataset: 'datasets.BSplinePoseMixReward'
returns_scale: 300.0
dt: 0.08
normalizer: 'GaussianNormalizer'
pose_only: True


# Model
diffusion: 'models.GaussianInvDynDiffusion'
returns_condition: True
clip_denoised: False

# Training
sample_freq: 10000
loss_type: 'state_l2'
train_data_loss: True
n_train_steps: 150000
inference_returns: 0

# Representation/visualization
renderer: 'utils.PathRenderer'
representation: 'cart'