# DATA
#dataset: 'kitchen-complete-v0'
#preprocess_fns: ['only_trajectory','joints_to_cart','cart_to_se3']

loader: 'datasets.GeneratedDataset'
dataset: 'datasets.BSplineDefault'
dt: 0.08
normalizer: 'GaussianNormalizer'
pose_only: True


# Model
diffusion: 'models.GaussianInvDynDiffusion'
returns_condition: False

# Training
sample_freq: 10000
loss_type: 'state_l2'
kinematic_loss: True
kinematic_scale: 100
max_kin_weight: 0.3
kin_weight_cutoff: 50
kin_norm: True
n_train_steps: 60000

# Representation/visualization
renderer: 'utils.PathRenderer'
representation: 'cart'