# DATA
#dataset: 'kitchen-complete-v0'
#preprocess_fns: ['only_trajectory','joints_to_cart','cart_to_se3']

loader: 'datasets.GeneratedDataset'
dataset: 'datasets.LinesPoseObstDense'
returns_scale: 100.0
dt: 0.08
normalizer: 'GaussianNormalizer'
pose_only: True


# Model
diffusion: 'models.GaussianInvDynDiffusion'
returns_condition: True
horizon: 32
clip_denoised: False
condition_indices:
  - 0
  - 'random'

# Training
sample_freq: 10000
loss_type: 'state_l2'
train_data_loss: True
n_train_steps: 150000
inference_returns: -0.01
inference_horizon: 100

dataset_val: 'datasets.LinesPoseObst'
val_batch_size: 64
val_nr_batch: 2

# Representation/visualization
renderer: 'utils.PathRenderer'
representation: 'cart'