# DATA
#dataset: 'kitchen-complete-v0'
#preprocess_fns: ['only_trajectory','joints_to_cart','cart_to_se3']

loader: 'datasets.GeneratedDataset'
dataset: 'datasets.BSplineDefault'

normalizer: 'CDFNormalizer'


# Model
diffusion: 'models.GaussianInvDynDiffusion'
returns_condition: False

# Training
sample_freq: 10000

# Representation/visualization
renderer: 'utils.PathRenderer'
representation: 'cart'