# DATA
#dataset: 'kitchen-complete-v0'
#preprocess_fns: ['only_trajectory','joints_to_cart','cart_to_se3']

loader: 'datasets.GeneratedDataset'
dataset: 'datasets.BSplineDefault'

normalizer: 'CDFNormalizer'


# Model
diffusion: 'models.SE3Diffusion'
returns_condition: False
gamma: 0.1

# Training
sample_freq: 10000
loss_type: 'state_l2'

# Representation/visualization
renderer: 'utils.PathRenderer'
representation: 'se3'